### ISSUE TITLE
A7 Astar/Shiden Inforgraphics and mentionings in infographics 

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#25]
Here is the contribution by infographics for March/May/June/July 2021.
https://t.me/ParachainNews/145	2k+	infographics + tw + tg
https://t.me/ParachainNews/433	5k+	Mentioning in daily Crowdloan infographics
https://t.me/ParachainNews/413	0.7k
https://twitter.com/PromoTeamPD/status/1402239374541078528?s=20		infographics
https://t.me/ParachainNews/486		Daily infographics
https://twitter.com/HuobiGlobal/status/1420565460194525188?s=20

**Comment by fiexer** [comment]
We only will list July in the spreadsheet.
Only this one is valid: https://t.me/ParachainNews/486 but has no tag or link to Shiden.

https://twitter.com/HuobiGlobal/status/1420565460194525188?s=20 is not valid because of no tweet of yourself or posted by PromoTeam. We cant reward tweets or videos posted by third parties.
